### PR TITLE
Fix/cookie banner domain

### LINKED ISSUE #2135: Cookie banner not hiding on non-pluralsight domain / envs (Flow sandbox, etc.)
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When clicking the dismiss "x" button on the [NavCookieBanner](https://design-system.pluralsight.com/components/nav#navcookiebanner), it will only dismiss on Pluralsight domains [due to this line](https://github.com/pluralsight/classic-design-system/blob/e3990e4560faf7f948851a49c2c979436085df7a/packages/navcookiebanner/src/react/index.tsx#L56).

### Expected behavior 🤔

Clicking the "x" button will dismiss the banner regardless of environment the app is running in.

### Steps to reproduce 🕹

Steps:

1. Visit https://sandbox-07.gitprime-ops.com/v2/org/gitprime/
2. Attempt closing the banner by clicking the x button

### Context 🔦

When testing the Flow app in sandbox, we are unable to click the banner away & it blocks other content behind it in some cases.

### Your environment 🌎

_No response_

### PR DESCRIPTION
**Pull request by Rykus0**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

closes #2135 
In test environments, cookie banner can't be dismissed due to hard-coded '.pluralsight.com' domain

## What is the new behavior?
Dynamically generate the cookie domain based on the current domain

### CODE REVIEW

File: packages/navcookiebanner/src/react/index.tsx [hunk 1]
```diff
@@ -51,9 +51,10 @@ const NavCookieBanner = React.forwardRef<HTMLDivElement, NavCookieBannerProps>(
     function dismiss() {
       const oneYear = new Date()
       oneYear.setFullYear(oneYear.getFullYear() + 1)
+      const domain = '.' + document.domain.replace(/^[^.]+\.(.*\..*)$/, '$1')
```
Comment (caseybaggz) [inline packages/navcookiebanner/src/react/index.tsx:54]: Let's add a comment above this line explaining the regex in a single sentence since it's so abstract. 👍

**Review by caseybaggz — APPROVED** [review]

**Review by caseybaggz — APPROVED** [review]
